controller_manager:
  ros__parameters:
    update_rate: 50

    diffdrive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diffdrive_controller:
  ros__parameters:
    publish_odom: false
    publish_odom_tf: false
    enable_odom_tf: false
    enable_odom_pub: false
    left_wheel_names: ["leftwheel_motor"]
    right_wheel_names: ["rightwheel_motor"]

    wheel_separation: 0.287
    wheel_radius: 0.033

    base_frame_id: base_link

    use_stamped_vel: false

    linear:
      x:
        max_velocity: 0.5

joint_state_broadcaster:
  ros__parameters:
    extra_joints:
      - lidar_sensor_secondary_motor
      - lidar_sensor_main_motor